language: cpp

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libasound2-dev
      compiler: gcc
      env: SOUND=sound.alsa
    - os: linux
      compiler: gcc
      env:
        - SOUND=sound.exe
        - WINCXX=i686-w64-mingw32-g++
    - os: osx
      env: SOUND=sound.mac

script:
  - make $SOUND && ls -l sound.*
