language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libasound2-dev
      compiler: gcc
      env: SOUND=sound.alsa
    - os: linux
      compiler: i686-w64-mingw32-g++
      addons:
        apt:
          packages:
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - g++-mingw-w64-i686
      env:
        - SOUND=sound.exe
        - WINCXX=i686-w64-mingw32-g++
    - os: osx
      env: SOUND=sound.mac

script:
  - ls /usr -l || true
  - ls /usr/i686-w64-mingw32/include -l || true
  - make $SOUND && ls -l sound.*
